### ISSUE TITLE
Mongodb 1.0.0 depends on async-std 1.5; tide depends on async-std 1.6

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/async-mongodb-session#1]
We either need to make it so Tide can work with older versions of async-std, or update mongodb to async-std 1.6+.

cc/ @saghm; most of the issues on async-std 1.6 have been fixed; are there any blockers on upgrading to a newer version? Is there anything I can do to help?

**Comment by saghm** [comment]
Hello! We're still getting a few more timeouts in CI than we were on async-std 1.5.x, but this might just be to our tests running in a very parallel way on resource constrained machines. Out of curiosity, are there any existing applications using Tide and MonogDB that might be able to test our update? The pull request I have to update to async-std 1.6.x is [here](https://github.com/mongodb/mongo-rust-driver/pull/182), so we'd definitely appreciate feedback we can get from real-world applications trying out that branch!

**Comment by yoshuawuyts** [comment]
> are there any existing applications using Tide and MonogDB that might be able to test our update?

I've asked around in our (async-std) Discord channel, directing them to this issue in case they do. I'll also give it a spin with my example app, and with this crate so we can provide some limited feedback.

**Comment by No9** [comment]
I've been running https://github.com/mongodb/mongo-rust-driver/pull/182 as part of a sample app i've been putting together https://github.com/No9/tide-morth-example/
I haven't noticed anything critical but it's not been heavily exercised.

FWIW I am building something more substantial based on the above so I will be keeping an eye on this topic.
