### ISSUE TITLE
provide option for using `async-std` runtime for mongodb

### ISSUE THREAD

**Issue by RagibHasin** [http-rs/async-mongodb-session#12]
As `mongodb` now supports `async-std` runtime besides `tokio` and the whole `async-*` ecosystem of crates usually use `async-std` as its default runtime, shouldn't this crate provide support for that runtime as well?

**Comment by lrlna** [comment]
This crate uses [mongodb's `async-std-runtime` feature flag](https://github.com/http-rs/async-mongodb-session/blob/master/Cargo.toml#L20) and therefore runs on `async-std`.

**Comment by RagibHasin** [comment]
Ah, sorry. I ran `cargo tree` and saw `tokio` in it and assumed as such. Found out why it is there.

Thanks for the quick response. I'm closing this issue.
