### ISSUE TITLE
Sessions aren't correctly stored

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/async-mongodb-session#3]
Each request we make creates a new session id entry in the database. It seems we're probably doing something wrong. The result is that the counter isn't updated and we keep opening new sessions.

Related issues: https://github.com/yoshuawuyts/async-mongodb-session/issues/1, https://github.com/http-rs/async-session/issues/10, https://github.com/http-rs/tide/pull/664

cc/ @lrlna

## Repro

1. Clone https://github.com/http-rs/tide/pull/664
2. `cargo run --example session`

## Screenshot

![Screenshot 2020-07-28 13 59 21](https://user-images.githubusercontent.com/2467194/88663431-e1a00f80-d0db-11ea-85bf-affc1c50c3a1.png)

**Comment by lrlna** [comment]
@yoshuawuyts when you store a session you should be updating an already existing session.

So [this line here](https://github.com/yoshuawuyts/async-mongodb-session/blob/master/src/lib.rs#L52) should do a [`find_one_and_update`](https://docs.rs/mongodb/1.0.0/mongodb/struct.Collection.html#method.find_one_and_update).

Something to consider for `store_session` function is whether this session would already exist when you store it, or there is a possibility of a brand new session. If there is a possibility of a brand new session, I'd do something like this:
- `find_one_and_update`. If there are no results returned, you know that this session doesn't exist.
- if the session doesn't exist, `insert_one` instead.

**Comment by mbroadst** [comment]
@lrlna sounds like you're talking about an upsert here, perhaps you're looking for [replace_one](https://docs.rs/mongodb/1.0.0/mongodb/options/struct.ReplaceOptions.html#structfield.upsert)

**Comment by yoshuawuyts** [comment]
@lrlna @mbroadst thanks heaps; tested and filed a fix in https://github.com/yoshuawuyts/async-mongodb-session/pull/4 :tada:

**Comment by lrlna** [comment]
@mbroadst i was precisely looking for an upsert but couldn't find `replace_one` in docs.rs 🤦‍♀️
