### ISSUE TITLE
`session` should be stored as an object instead of a string

### ISSUE THREAD

**Issue by lrlna** [http-rs/async-mongodb-session#6]
When testing some things for mongosh, I found that we are storing `session` as a string. It'd be better for us to store this as an object.
`
<img width="825" alt="Screenshot 2020-09-14 112035" src="https://user-images.githubusercontent.com/8107784/93068190-6fc85900-f67c-11ea-86ba-77902c5729bd.png">

**Comment by yoshuawuyts** [comment]
Oh great point; thanks!
